"""Initial CRM Schema

Revision ID: 1e8e7e3348fc
Revises: 
Create Date: 2026-06-27 12:56:40.333302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e8e7e3348fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_book_entries',
    sa.Column('price_book_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['price_book_id'], ['price_books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_book_entries_id'), 'price_book_entries', ['id'], unique=False)
    op.create_index(op.f('ix_price_book_entries_price_book_id'), 'price_book_entries', ['price_book_id'], unique=False)
    op.create_index(op.f('ix_price_book_entries_product_id'), 'price_book_entries', ['product_id'], unique=False)
    op.drop_table('custom_fields')
    op.drop_table('territory_users')
    op.drop_table('notes')
    op.drop_table('workflows')
    op.drop_table('territories')
    op.drop_table('integrations')
    op.drop_table('knowledge_base')
    op.drop_table('calls')
    op.drop_table('tags')
    op.drop_table('campaigns')
    op.drop_table('price_book_products')
    op.drop_table('email_logs')
    op.drop_table('support_tickets')
    op.drop_table('calendar_events')
    op.drop_table('tasks')
    op.drop_table('sales_order_items')
    op.drop_table('payments')
    op.drop_table('invoices')
    op.drop_table('teams')
    op.drop_table('meetings')
    op.drop_table('team_members')
    op.drop_table('ticket_comments')
    op.drop_table('sales_orders')
    op.drop_table('documents')
    op.drop_table('record_tags')
    op.add_column('accounts', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('accounts', sa.Column('type', sa.Enum('PROSPECT', 'CUSTOMER', 'PARTNER', 'VENDOR', 'COMPETITOR', 'OTHER', name='accounttype'), nullable=False))
    op.add_column('accounts', sa.Column('billing_street', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('billing_city', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('billing_state', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('billing_country', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('billing_pincode', sa.String(length=20), nullable=True))
    op.add_column('accounts', sa.Column('shipping_street', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('shipping_city', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('shipping_state', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('shipping_country', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('shipping_pincode', sa.String(length=20), nullable=True))
    op.add_column('accounts', sa.Column('annual_revenue', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('accounts', sa.Column('employee_count', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('gst_number', sa.String(length=20), nullable=True))
    op.add_column('accounts', sa.Column('pan_number', sa.String(length=20), nullable=True))
    op.add_column('accounts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('accounts', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('accounts', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('accounts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('accounts', 'industry',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('TECHNOLOGY', 'FINANCE', 'HEALTHCARE', 'EDUCATION', 'MANUFACTURING', 'RETAIL', 'REAL_ESTATE', 'HOSPITALITY', 'LOGISTICS', 'OTHER', name='accountindustry'),
               existing_nullable=True)
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_accounts_type'), 'accounts', ['type'], unique=False)
    op.drop_constraint(op.f('accounts_assigned_manager_fkey'), 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('accounts', 'account_name')
    op.drop_column('accounts', 'shipping_address')
    op.drop_column('accounts', 'billing_address')
    op.drop_column('accounts', 'assigned_manager')
    op.add_column('audit_logs', sa.Column('entity_type', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('entity_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CREATED', 'UPDATED', 'DELETED', 'VIEWED', name='auditaction'),
               nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'new_value')
    op.drop_column('audit_logs', 'module_name')
    op.drop_column('audit_logs', 'record_id')
    op.drop_column('audit_logs', 'old_value')
    op.add_column('contacts', sa.Column('salutation', sa.Enum('MR', 'MRS', 'MS', 'DR', 'PROF', name='contactsalutation'), nullable=True))
    op.add_column('contacts', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('contacts', sa.Column('mailing_street', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('mailing_city', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('mailing_state', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('mailing_country', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('mailing_pincode', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='contactstatus'), nullable=False))
    op.add_column('contacts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('do_not_email', sa.Boolean(), nullable=False))
    op.add_column('contacts', sa.Column('do_not_call', sa.Boolean(), nullable=False))
    op.add_column('contacts', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.add_column('contacts', sa.Column('reported_to_id', sa.UUID(), nullable=True))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('contacts', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('contacts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('contacts', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contacts', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_contacts_account_id'), 'contacts', ['account_id'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_owner_id'), 'contacts', ['owner_id'], unique=False)
    op.drop_constraint(op.f('contacts_account_id_fkey'), 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'contacts', 'contacts', ['reported_to_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'contacts', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('contacts', 'designation')
    op.add_column('lead_activities', sa.Column('type', sa.Enum('CALL', 'EMAIL', 'MEETING', 'DEMO', 'FOLLOW_UP', 'OTHER', name='activitytype'), nullable=False))
    op.add_column('lead_activities', sa.Column('outcome', sa.Enum('INTERESTED', 'NOT_INTERESTED', 'CALLBACK', 'NO_ANSWER', 'LEFT_MESSAGE', 'OTHER', name='activityoutcome'), nullable=True))
    op.add_column('lead_activities', sa.Column('subject', sa.String(length=255), nullable=False))
    op.add_column('lead_activities', sa.Column('duration_minutes', sa.String(length=10), nullable=True))
    op.add_column('lead_activities', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('lead_activities', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('lead_activities', 'lead_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('lead_activities', 'activity_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_lead_activities_id'), 'lead_activities', ['id'], unique=False)
    op.create_index(op.f('ix_lead_activities_lead_id'), 'lead_activities', ['lead_id'], unique=False)
    op.drop_constraint(op.f('lead_activities_lead_id_fkey'), 'lead_activities', type_='foreignkey')
    op.drop_constraint(op.f('lead_activities_user_id_fkey'), 'lead_activities', type_='foreignkey')
    op.create_foreign_key(None, 'lead_activities', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_activities', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('lead_activities', 'activity_type')
    op.add_column('lead_notes', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('lead_notes', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('lead_notes', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.add_column('lead_notes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('lead_notes', 'lead_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('lead_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_lead_notes_id'), 'lead_notes', ['id'], unique=False)
    op.create_index(op.f('ix_lead_notes_lead_id'), 'lead_notes', ['lead_id'], unique=False)
    op.drop_constraint(op.f('lead_notes_lead_id_fkey'), 'lead_notes', type_='foreignkey')
    op.drop_constraint(op.f('lead_notes_created_by_fkey'), 'lead_notes', type_='foreignkey')
    op.create_foreign_key(None, 'lead_notes', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_notes', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('lead_notes', 'note')
    op.drop_column('lead_notes', 'created_by')
    op.add_column('lead_sources', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('lead_sources', sa.Column('type', sa.Enum('WEBSITE', 'COLD_CALL', 'REFERRAL', 'SOCIAL_MEDIA', 'EMAIL_CAMPAIGN', 'TRADE_SHOW', 'ADVERTISEMENT', 'PARTNER', 'OTHER', name='leadsourcetype'), nullable=False))
    op.add_column('lead_sources', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('lead_sources', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('lead_sources', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('lead_sources', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_lead_sources_id'), 'lead_sources', ['id'], unique=False)
    op.create_unique_constraint(None, 'lead_sources', ['name'])
    op.drop_column('lead_sources', 'source_name')
    op.add_column('leads', sa.Column('salutation', sa.String(length=10), nullable=True))
    op.add_column('leads', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('status', sa.Enum('NEW', 'ASSIGNED', 'IN_PROCESS', 'CONVERTED', 'RECYCLED', 'DEAD', name='leadstatus'), nullable=False))
    op.add_column('leads', sa.Column('rating', sa.Enum('HOT', 'WARM', 'COLD', name='leadrating'), nullable=True))
    op.add_column('leads', sa.Column('annual_revenue', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('leads', sa.Column('no_of_employees', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('is_converted', sa.Boolean(), nullable=False))
    op.add_column('leads', sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('converted_account_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('converted_contact_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('converted_opportunity_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('account_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('contact_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('assigned_to_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('leads', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('leads', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('leads', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_leads_assigned_to_id'), 'leads', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_is_converted'), 'leads', ['is_converted'], unique=False)
    op.create_index(op.f('ix_leads_source_id'), 'leads', ['source_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.drop_constraint(op.f('leads_assigned_to_fkey'), 'leads', type_='foreignkey')
    op.drop_constraint(op.f('leads_source_id_fkey'), 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'contacts', ['converted_contact_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'accounts', ['converted_account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'lead_sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.drop_column('leads', 'company_name')
    op.drop_column('leads', 'lead_status')
    op.drop_column('leads', 'lead_score')
    op.drop_column('leads', 'notes')
    op.drop_column('leads', 'assigned_to')
    op.drop_column('leads', 'expected_value')
    op.add_column('notifications', sa.Column('notification_type', sa.Enum('INFO', 'WARNING', 'SUCCESS', 'ERROR', name='notificationtype'), nullable=False))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('notifications', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('opportunities', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('opportunities', sa.Column('type', sa.Enum('NEW_BUSINESS', 'EXISTING_BUSINESS', 'RENEWAL', 'UPSELL', 'CROSS_SELL', name='opportunitytype'), nullable=True))
    op.add_column('opportunities', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('opportunities', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('opportunities', sa.Column('close_date', sa.Date(), nullable=False))
    op.add_column('opportunities', sa.Column('actual_close_date', sa.Date(), nullable=True))
    op.add_column('opportunities', sa.Column('is_won', sa.Boolean(), nullable=True))
    op.add_column('opportunities', sa.Column('loss_reason', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('competitor', sa.String(length=255), nullable=True))
    op.add_column('opportunities', sa.Column('contact_id', sa.UUID(), nullable=True))
    op.add_column('opportunities', sa.Column('lead_id', sa.UUID(), nullable=True))
    op.add_column('opportunities', sa.Column('price_book_id', sa.UUID(), nullable=True))
    op.add_column('opportunities', sa.Column('assigned_to_id', sa.UUID(), nullable=True))
    op.add_column('opportunities', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('opportunities', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('opportunities', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('opportunities', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('opportunities', 'stage',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('PROSPECTING', 'QUALIFICATION', 'NEEDS_ANALYSIS', 'VALUE_PROPOSITION', 'ID_DECISION_MAKERS', 'PERCEPTION_ANALYSIS', 'PROPOSAL', 'NEGOTIATION', 'CLOSED_WON', 'CLOSED_LOST', name='opportunitystage'),
               nullable=False)
    op.alter_column('opportunities', 'probability',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('opportunities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_opportunities_account_id'), 'opportunities', ['account_id'], unique=False)
    op.create_index(op.f('ix_opportunities_assigned_to_id'), 'opportunities', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_name'), 'opportunities', ['name'], unique=False)
    op.create_index(op.f('ix_opportunities_stage'), 'opportunities', ['stage'], unique=False)
    op.drop_constraint(op.f('opportunities_owner_id_fkey'), 'opportunities', type_='foreignkey')
    op.drop_constraint(op.f('opportunities_account_id_fkey'), 'opportunities', type_='foreignkey')
    op.create_foreign_key(None, 'opportunities', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'opportunities', 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'opportunities', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'opportunities', 'price_books', ['price_book_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'opportunities', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'opportunities', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    op.drop_column('opportunities', 'expected_close_date')
    op.drop_column('opportunities', 'opportunity_name')
    op.drop_column('opportunities', 'owner_id')
    op.add_column('opportunity_products', sa.Column('price_book_entry_id', sa.UUID(), nullable=True))
    op.add_column('opportunity_products', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('opportunity_products', sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('opportunity_products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('opportunity_products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('opportunity_products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('opportunity_products', 'opportunity_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('opportunity_products', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('opportunity_products', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
    op.alter_column('opportunity_products', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=False)
    op.alter_column('opportunity_products', 'total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=False)
    op.create_index(op.f('ix_opportunity_products_id'), 'opportunity_products', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_products_opportunity_id'), 'opportunity_products', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_products_product_id'), 'opportunity_products', ['product_id'], unique=False)
    op.drop_constraint(op.f('opportunity_products_product_id_fkey'), 'opportunity_products', type_='foreignkey')
    op.drop_constraint(op.f('opportunity_products_opportunity_id_fkey'), 'opportunity_products', type_='foreignkey')
    op.create_foreign_key(None, 'opportunity_products', 'opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'opportunity_products', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'opportunity_products', 'price_book_entries', ['price_book_entry_id'], ['id'], ondelete='SET NULL')
    op.add_column('permissions', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('permissions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('permissions', sa.Column('resource', sa.String(length=50), nullable=False))
    op.add_column('permissions', sa.Column('action', sa.String(length=50), nullable=False))
    op.add_column('permissions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('permissions_permission_name_key'), 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_unique_constraint('uq_permission_resource_action', 'permissions', ['resource', 'action'])
    op.drop_column('permissions', 'permission_name')
    op.drop_column('permissions', 'module_name')
    op.add_column('price_books', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('price_books', sa.Column('is_standard', sa.Boolean(), nullable=False))
    op.add_column('price_books', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('price_books', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('price_books', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('price_books', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('price_books', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('price_books', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_price_books_id'), 'price_books', ['id'], unique=False)
    op.create_unique_constraint(None, 'price_books', ['name'])
    op.drop_column('price_books', 'book_name')
    op.add_column('products', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('products', sa.Column('code', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('category', sa.Enum('SOFTWARE', 'HARDWARE', 'SERVICE', 'SUBSCRIPTION', 'CONSULTING', 'SUPPORT', 'OTHER', name='productcategory'), nullable=True))
    op.add_column('products', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISCONTINUED', name='productstatus'), nullable=False))
    op.add_column('products', sa.Column('list_price', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('products', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('products', sa.Column('has_inventory', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('quantity_in_stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('units_sold', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('products', sa.Column('hsn_code', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_unique_constraint(None, 'products', ['code'])
    op.drop_column('products', 'product_name')
    op.drop_column('products', 'price')
    op.drop_column('products', 'sku')
    op.add_column('quotation_items', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.add_column('quotation_items', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('quotation_items', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('quotation_items', sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('quotation_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('quotation_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('quotation_items', 'quotation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('quotation_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('quotation_items', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
    op.alter_column('quotation_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=False)
    op.alter_column('quotation_items', 'total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=False)
    op.create_index(op.f('ix_quotation_items_id'), 'quotation_items', ['id'], unique=False)
    op.create_index(op.f('ix_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False)
    op.drop_constraint(op.f('quotation_items_quotation_id_fkey'), 'quotation_items', type_='foreignkey')
    op.drop_constraint(op.f('quotation_items_product_id_fkey'), 'quotation_items', type_='foreignkey')
    op.create_foreign_key(None, 'quotation_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'quotation_items', 'quotations', ['quotation_id'], ['id'], ondelete='CASCADE')
    op.add_column('quotations', sa.Column('subject', sa.String(length=255), nullable=False))
    op.add_column('quotations', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quotations', sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('quotations', sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('quotations', sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('quotations', sa.Column('shipping_amount', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('quotations', sa.Column('grand_total', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('quotations', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('quotations', sa.Column('terms_and_conditions', sa.Text(), nullable=True))
    op.add_column('quotations', sa.Column('payment_terms', sa.String(length=255), nullable=True))
    op.add_column('quotations', sa.Column('delivery_terms', sa.String(length=255), nullable=True))
    op.add_column('quotations', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('quotations', sa.Column('account_id', sa.UUID(), nullable=True))
    op.add_column('quotations', sa.Column('contact_id', sa.UUID(), nullable=True))
    op.add_column('quotations', sa.Column('price_book_id', sa.UUID(), nullable=True))
    op.add_column('quotations', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('quotations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('quotations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('quotations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('quotations', 'quote_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('quotations', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='quotationstatus'),
               nullable=False)
    op.alter_column('quotations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('quotations_quote_number_key'), 'quotations', type_='unique')
    op.create_index(op.f('ix_quotations_account_id'), 'quotations', ['account_id'], unique=False)
    op.create_index(op.f('ix_quotations_id'), 'quotations', ['id'], unique=False)
    op.create_index(op.f('ix_quotations_opportunity_id'), 'quotations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_quotations_quote_number'), 'quotations', ['quote_number'], unique=True)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.drop_constraint(op.f('quotations_opportunity_id_fkey'), 'quotations', type_='foreignkey')
    op.create_foreign_key(None, 'quotations', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'quotations', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'quotations', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'quotations', 'opportunities', ['opportunity_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'quotations', 'price_books', ['price_book_id'], ['id'], ondelete='SET NULL')
    op.drop_column('quotations', 'total_amount')
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.add_column('roles', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('roles_role_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_column('roles', 'role_name')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'INVITED', name='userstatus'), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('language', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'language')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'status')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'hashed_password')
    op.add_column('roles', sa.Column('role_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_unique_constraint(op.f('roles_role_name_key'), 'roles', ['role_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'name')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.add_column('quotations', sa.Column('total_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.create_foreign_key(op.f('quotations_opportunity_id_fkey'), 'quotations', 'opportunities', ['opportunity_id'], ['id'])
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quote_number'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_opportunity_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_account_id'), table_name='quotations')
    op.create_unique_constraint(op.f('quotations_quote_number_key'), 'quotations', ['quote_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('quotations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('quotations', 'status',
               existing_type=sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='quotationstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('quotations', 'quote_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('quotations', 'deleted_at')
    op.drop_column('quotations', 'is_deleted')
    op.drop_column('quotations', 'updated_at')
    op.drop_column('quotations', 'created_by_id')
    op.drop_column('quotations', 'price_book_id')
    op.drop_column('quotations', 'contact_id')
    op.drop_column('quotations', 'account_id')
    op.drop_column('quotations', 'notes')
    op.drop_column('quotations', 'delivery_terms')
    op.drop_column('quotations', 'payment_terms')
    op.drop_column('quotations', 'terms_and_conditions')
    op.drop_column('quotations', 'currency')
    op.drop_column('quotations', 'grand_total')
    op.drop_column('quotations', 'shipping_amount')
    op.drop_column('quotations', 'tax_amount')
    op.drop_column('quotations', 'discount_amount')
    op.drop_column('quotations', 'subtotal')
    op.drop_column('quotations', 'sent_at')
    op.drop_column('quotations', 'subject')
    op.drop_constraint(None, 'quotation_items', type_='foreignkey')
    op.drop_constraint(None, 'quotation_items', type_='foreignkey')
    op.create_foreign_key(op.f('quotation_items_product_id_fkey'), 'quotation_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('quotation_items_quotation_id_fkey'), 'quotation_items', 'quotations', ['quotation_id'], ['id'])
    op.drop_index(op.f('ix_quotation_items_quotation_id'), table_name='quotation_items')
    op.drop_index(op.f('ix_quotation_items_id'), table_name='quotation_items')
    op.alter_column('quotation_items', 'total_price',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('quotation_items', 'unit_price',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('quotation_items', 'quantity',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('quotation_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('quotation_items', 'quotation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('quotation_items', 'updated_at')
    op.drop_column('quotation_items', 'created_at')
    op.drop_column('quotation_items', 'tax_percent')
    op.drop_column('quotation_items', 'discount_percent')
    op.drop_column('quotation_items', 'description')
    op.drop_column('quotation_items', 'sort_order')
    op.add_column('products', sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'is_deleted')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'hsn_code')
    op.drop_column('products', 'tax_rate')
    op.drop_column('products', 'units_sold')
    op.drop_column('products', 'quantity_in_stock')
    op.drop_column('products', 'has_inventory')
    op.drop_column('products', 'currency')
    op.drop_column('products', 'cost_price')
    op.drop_column('products', 'list_price')
    op.drop_column('products', 'status')
    op.drop_column('products', 'category')
    op.drop_column('products', 'code')
    op.drop_column('products', 'name')
    op.add_column('price_books', sa.Column('book_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'price_books', type_='unique')
    op.drop_index(op.f('ix_price_books_id'), table_name='price_books')
    op.drop_column('price_books', 'deleted_at')
    op.drop_column('price_books', 'is_deleted')
    op.drop_column('price_books', 'updated_at')
    op.drop_column('price_books', 'created_at')
    op.drop_column('price_books', 'currency')
    op.drop_column('price_books', 'is_active')
    op.drop_column('price_books', 'is_standard')
    op.drop_column('price_books', 'name')
    op.add_column('permissions', sa.Column('module_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('permissions', sa.Column('permission_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint('uq_permission_resource_action', 'permissions', type_='unique')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.create_unique_constraint(op.f('permissions_permission_name_key'), 'permissions', ['permission_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'created_at')
    op.drop_column('permissions', 'action')
    op.drop_column('permissions', 'resource')
    op.drop_column('permissions', 'description')
    op.drop_column('permissions', 'name')
    op.drop_constraint(None, 'opportunity_products', type_='foreignkey')
    op.drop_constraint(None, 'opportunity_products', type_='foreignkey')
    op.drop_constraint(None, 'opportunity_products', type_='foreignkey')
    op.create_foreign_key(op.f('opportunity_products_opportunity_id_fkey'), 'opportunity_products', 'opportunities', ['opportunity_id'], ['id'])
    op.create_foreign_key(op.f('opportunity_products_product_id_fkey'), 'opportunity_products', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_opportunity_products_product_id'), table_name='opportunity_products')
    op.drop_index(op.f('ix_opportunity_products_opportunity_id'), table_name='opportunity_products')
    op.drop_index(op.f('ix_opportunity_products_id'), table_name='opportunity_products')
    op.alter_column('opportunity_products', 'total_price',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('opportunity_products', 'unit_price',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('opportunity_products', 'quantity',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('opportunity_products', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('opportunity_products', 'opportunity_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('opportunity_products', 'updated_at')
    op.drop_column('opportunity_products', 'created_at')
    op.drop_column('opportunity_products', 'description')
    op.drop_column('opportunity_products', 'tax_percent')
    op.drop_column('opportunity_products', 'discount_percent')
    op.drop_column('opportunity_products', 'price_book_entry_id')
    op.add_column('opportunities', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('opportunity_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('expected_close_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.create_foreign_key(op.f('opportunities_account_id_fkey'), 'opportunities', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(op.f('opportunities_owner_id_fkey'), 'opportunities', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_opportunities_stage'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_name'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_assigned_to_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_account_id'), table_name='opportunities')
    op.alter_column('opportunities', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('opportunities', 'probability',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('opportunities', 'stage',
               existing_type=sa.Enum('PROSPECTING', 'QUALIFICATION', 'NEEDS_ANALYSIS', 'VALUE_PROPOSITION', 'ID_DECISION_MAKERS', 'PERCEPTION_ANALYSIS', 'PROPOSAL', 'NEGOTIATION', 'CLOSED_WON', 'CLOSED_LOST', name='opportunitystage'),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('opportunities', 'deleted_at')
    op.drop_column('opportunities', 'is_deleted')
    op.drop_column('opportunities', 'updated_at')
    op.drop_column('opportunities', 'created_by_id')
    op.drop_column('opportunities', 'assigned_to_id')
    op.drop_column('opportunities', 'price_book_id')
    op.drop_column('opportunities', 'lead_id')
    op.drop_column('opportunities', 'contact_id')
    op.drop_column('opportunities', 'competitor')
    op.drop_column('opportunities', 'loss_reason')
    op.drop_column('opportunities', 'is_won')
    op.drop_column('opportunities', 'actual_close_date')
    op.drop_column('opportunities', 'close_date')
    op.drop_column('opportunities', 'currency')
    op.drop_column('opportunities', 'amount')
    op.drop_column('opportunities', 'description')
    op.drop_column('opportunities', 'type')
    op.drop_column('opportunities', 'name')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('notifications', 'deleted_at')
    op.drop_column('notifications', 'is_deleted')
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'notification_type')
    op.add_column('leads', sa.Column('expected_value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('lead_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('lead_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key(op.f('leads_source_id_fkey'), 'leads', 'lead_sources', ['source_id'], ['id'])
    op.create_foreign_key(op.f('leads_assigned_to_fkey'), 'leads', 'users', ['assigned_to'], ['id'])
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_source_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_is_converted'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to_id'), table_name='leads')
    op.alter_column('leads', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('leads', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('leads', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('leads', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('leads', 'deleted_at')
    op.drop_column('leads', 'is_deleted')
    op.drop_column('leads', 'created_by_id')
    op.drop_column('leads', 'assigned_to_id')
    op.drop_column('leads', 'contact_id')
    op.drop_column('leads', 'account_id')
    op.drop_column('leads', 'converted_opportunity_id')
    op.drop_column('leads', 'converted_contact_id')
    op.drop_column('leads', 'converted_account_id')
    op.drop_column('leads', 'converted_at')
    op.drop_column('leads', 'is_converted')
    op.drop_column('leads', 'description')
    op.drop_column('leads', 'industry')
    op.drop_column('leads', 'no_of_employees')
    op.drop_column('leads', 'annual_revenue')
    op.drop_column('leads', 'rating')
    op.drop_column('leads', 'status')
    op.drop_column('leads', 'website')
    op.drop_column('leads', 'mobile')
    op.drop_column('leads', 'title')
    op.drop_column('leads', 'company')
    op.drop_column('leads', 'salutation')
    op.add_column('lead_sources', sa.Column('source_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lead_sources', type_='unique')
    op.drop_index(op.f('ix_lead_sources_id'), table_name='lead_sources')
    op.drop_column('lead_sources', 'updated_at')
    op.drop_column('lead_sources', 'created_at')
    op.drop_column('lead_sources', 'is_active')
    op.drop_column('lead_sources', 'description')
    op.drop_column('lead_sources', 'type')
    op.drop_column('lead_sources', 'name')
    op.add_column('lead_notes', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('lead_notes', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lead_notes', type_='foreignkey')
    op.drop_constraint(None, 'lead_notes', type_='foreignkey')
    op.create_foreign_key(op.f('lead_notes_created_by_fkey'), 'lead_notes', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('lead_notes_lead_id_fkey'), 'lead_notes', 'leads', ['lead_id'], ['id'])
    op.drop_index(op.f('ix_lead_notes_lead_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_id'), table_name='lead_notes')
    op.alter_column('lead_notes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lead_notes', 'lead_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('lead_notes', 'updated_at')
    op.drop_column('lead_notes', 'is_pinned')
    op.drop_column('lead_notes', 'content')
    op.drop_column('lead_notes', 'user_id')
    op.add_column('lead_activities', sa.Column('activity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lead_activities', type_='foreignkey')
    op.drop_constraint(None, 'lead_activities', type_='foreignkey')
    op.create_foreign_key(op.f('lead_activities_user_id_fkey'), 'lead_activities', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('lead_activities_lead_id_fkey'), 'lead_activities', 'leads', ['lead_id'], ['id'])
    op.drop_index(op.f('ix_lead_activities_lead_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_id'), table_name='lead_activities')
    op.alter_column('lead_activities', 'activity_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('lead_activities', 'lead_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('lead_activities', 'updated_at')
    op.drop_column('lead_activities', 'created_at')
    op.drop_column('lead_activities', 'duration_minutes')
    op.drop_column('lead_activities', 'subject')
    op.drop_column('lead_activities', 'outcome')
    op.drop_column('lead_activities', 'type')
    op.add_column('contacts', sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key(op.f('contacts_account_id_fkey'), 'contacts', 'accounts', ['account_id'], ['id'])
    op.drop_index(op.f('ix_contacts_owner_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_account_id'), table_name='contacts')
    op.alter_column('contacts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('contacts', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('contacts', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('contacts', 'deleted_at')
    op.drop_column('contacts', 'is_deleted')
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'reported_to_id')
    op.drop_column('contacts', 'owner_id')
    op.drop_column('contacts', 'do_not_call')
    op.drop_column('contacts', 'do_not_email')
    op.drop_column('contacts', 'description')
    op.drop_column('contacts', 'status')
    op.drop_column('contacts', 'mailing_pincode')
    op.drop_column('contacts', 'mailing_country')
    op.drop_column('contacts', 'mailing_state')
    op.drop_column('contacts', 'mailing_city')
    op.drop_column('contacts', 'mailing_street')
    op.drop_column('contacts', 'date_of_birth')
    op.drop_column('contacts', 'linkedin_url')
    op.drop_column('contacts', 'mobile')
    op.drop_column('contacts', 'department')
    op.drop_column('contacts', 'title')
    op.drop_column('contacts', 'salutation')
    op.add_column('audit_logs', sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('module_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.Enum('CREATED', 'UPDATED', 'DELETED', 'VIEWED', name='auditaction'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('audit_logs', 'updated_at')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    op.add_column('accounts', sa.Column('assigned_manager', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('billing_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('shipping_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('account_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key(op.f('accounts_assigned_manager_fkey'), 'accounts', 'users', ['assigned_manager'], ['id'])
    op.drop_index(op.f('ix_accounts_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.alter_column('accounts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('accounts', 'industry',
               existing_type=sa.Enum('TECHNOLOGY', 'FINANCE', 'HEALTHCARE', 'EDUCATION', 'MANUFACTURING', 'RETAIL', 'REAL_ESTATE', 'HOSPITALITY', 'LOGISTICS', 'OTHER', name='accountindustry'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('accounts', 'deleted_at')
    op.drop_column('accounts', 'is_deleted')
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'owner_id')
    op.drop_column('accounts', 'description')
    op.drop_column('accounts', 'pan_number')
    op.drop_column('accounts', 'gst_number')
    op.drop_column('accounts', 'employee_count')
    op.drop_column('accounts', 'annual_revenue')
    op.drop_column('accounts', 'shipping_pincode')
    op.drop_column('accounts', 'shipping_country')
    op.drop_column('accounts', 'shipping_state')
    op.drop_column('accounts', 'shipping_city')
    op.drop_column('accounts', 'shipping_street')
    op.drop_column('accounts', 'billing_pincode')
    op.drop_column('accounts', 'billing_country')
    op.drop_column('accounts', 'billing_state')
    op.drop_column('accounts', 'billing_city')
    op.drop_column('accounts', 'billing_street')
    op.drop_column('accounts', 'type')
    op.drop_column('accounts', 'name')
    op.create_table('record_tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('module_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('record_tags_tag_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('record_tags_pkey'))
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('module_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('documents_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_table('sales_orders',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quotation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('order_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('sales_orders_quotation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_orders_pkey')),
    sa.UniqueConstraint('order_number', name=op.f('sales_orders_order_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ticket_comments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], name=op.f('ticket_comments_ticket_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ticket_comments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ticket_comments_pkey'))
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('team_members_team_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('team_members_user_id_fkey')),
    sa.PrimaryKeyConstraint('team_id', 'user_id', name=op.f('team_members_pkey'))
    )
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organizer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('meeting_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meeting_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('meetings_account_id_fkey')),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], name=op.f('meetings_organizer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meetings_pkey'))
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('team_lead', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_lead'], ['users.id'], name=op.f('teams_team_lead_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('teams_pkey'))
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sales_order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name=op.f('invoices_sales_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invoices_pkey')),
    sa.UniqueConstraint('invoice_number', name=op.f('invoices_invoice_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('payment_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transaction_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('payments_invoice_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey'))
    )
    op.create_table('sales_order_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sales_order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('sales_order_items_product_id_fkey')),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name=op.f('sales_order_items_sales_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_order_items_pkey'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('tasks_account_id_fkey')),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('tasks_assigned_to_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('calendar_events_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('calendar_events_pkey'))
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ticket_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('support_tickets_account_id_fkey')),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('support_tickets_assigned_to_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('support_tickets_pkey')),
    sa.UniqueConstraint('ticket_number', name=op.f('support_tickets_ticket_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('email_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sent_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('recipient_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], name=op.f('email_logs_sent_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('email_logs_pkey'))
    )
    op.create_table('price_book_products',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price_book_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('custom_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['price_book_id'], ['price_books.id'], name=op.f('price_book_products_price_book_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('price_book_products_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('price_book_products_pkey'))
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('campaign_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('campaign_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('budget', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('campaigns_pkey'))
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey'))
    )
    op.create_table('calls',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('call_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('call_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('calls_account_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('calls_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('calls_pkey'))
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('knowledge_base_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_base_pkey'))
    )
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('integration_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('integrations_pkey'))
    )
    op.create_table('territories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('territory_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('parent_territory', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_territory'], ['territories.id'], name=op.f('territories_parent_territory_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('territories_pkey'))
    )
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workflow_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('trigger_module', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('trigger_event', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workflows_pkey'))
    )
    op.create_table('notes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('module_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('notes_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notes_pkey'))
    )
    op.create_table('territory_users',
    sa.Column('territory_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], name=op.f('territory_users_territory_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('territory_users_user_id_fkey')),
    sa.PrimaryKeyConstraint('territory_id', 'user_id', name=op.f('territory_users_pkey'))
    )
    op.create_table('custom_fields',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('module_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('field_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('custom_fields_pkey'))
    )
    op.drop_index(op.f('ix_price_book_entries_product_id'), table_name='price_book_entries')
    op.drop_index(op.f('ix_price_book_entries_price_book_id'), table_name='price_book_entries')
    op.drop_index(op.f('ix_price_book_entries_id'), table_name='price_book_entries')
    op.drop_table('price_book_entries')
    # ### end Alembic commands ###
