"""Add SalesOrder fields and SalesOrderItem

Revision ID: 3b60d7c5ab69
Revises: dbb55e7e51ec
Create Date: 2026-07-06 16:41:56.666227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b60d7c5ab69'
down_revision: Union[str, Sequence[str], None] = 'dbb55e7e51ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('STANDARD', 'EXPRESS', 'URGENT', name='salesorderpriority').create(op.get_bind())
    sa.Enum('PENDING', 'PAID', 'OVERDUE', name='salesorderpaymentstatus').create(op.get_bind())
    op.create_table('sales_order_items',
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_items_id'), 'sales_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_sales_order_items_sales_order_id'), 'sales_order_items', ['sales_order_id'], unique=False)
    op.add_column('sales_orders', sa.Column('priority', sa.Enum('STANDARD', 'EXPRESS', 'URGENT', name='salesorderpriority'), nullable=False))
    op.add_column('sales_orders', sa.Column('order_date', sa.Date(), nullable=True))
    op.add_column('sales_orders', sa.Column('ship_date', sa.Date(), nullable=True))
    op.add_column('sales_orders', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.add_column('sales_orders', sa.Column('ship_to', sa.Text(), nullable=True))
    op.add_column('sales_orders', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('sales_orders', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('sales_orders', sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'OVERDUE', name='salesorderpaymentstatus'), nullable=False))
    op.add_column('sales_orders', sa.Column('payment_method', sa.String(length=100), nullable=True))
    op.add_column('sales_orders', sa.Column('assignee_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sales_orders', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tasks', 'task_type',
               existing_type=postgresql.ENUM('email', 'task', 'meeting', 'follow_up', 'call', name='tasktype'),
               nullable=False,
               existing_server_default=sa.text("'task'::tasktype"))
    op.create_index(op.f('ix_tasks_account_id'), 'tasks', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_account_id'), table_name='tasks')
    op.alter_column('tasks', 'task_type',
               existing_type=postgresql.ENUM('email', 'task', 'meeting', 'follow_up', 'call', name='tasktype'),
               nullable=True,
               existing_server_default=sa.text("'task'::tasktype"))
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_column('sales_orders', 'assignee_id')
    op.drop_column('sales_orders', 'payment_method')
    op.drop_column('sales_orders', 'payment_status')
    op.drop_column('sales_orders', 'tags')
    op.drop_column('sales_orders', 'notes')
    op.drop_column('sales_orders', 'ship_to')
    op.drop_column('sales_orders', 'delivery_date')
    op.drop_column('sales_orders', 'ship_date')
    op.drop_column('sales_orders', 'order_date')
    op.drop_column('sales_orders', 'priority')
    op.drop_index(op.f('ix_sales_order_items_sales_order_id'), table_name='sales_order_items')
    op.drop_index(op.f('ix_sales_order_items_id'), table_name='sales_order_items')
    op.drop_table('sales_order_items')
    sa.Enum(name='salesorderpriority').drop(op.get_bind())
    sa.Enum(name='salesorderpaymentstatus').drop(op.get_bind())
    # ### end Alembic commands ###
